role_category_list: ["Backoffice", "Development"]
role_category:
  backoffice: "Backoffice"
  development: "Development"

role_list: ["HR", "Manager", "Leader", "Member"]
role:
  hr: "HR"
  manager: "Manager"
  leader: "Leader"
  member: "Member"

positions: [["Chief", "chief"], ["Manager", "manager"], ["Submanager", "submanager"], ["Leader", "leader"], ["Subleader", "subleader"], ["Member", "member"]]

master_datas: ["groups", "report_categories", "vacation_types"]

questions: [["Leader", "leader"], ["Subleader", "subleader"], ["Member", "member"]]

project:
  states: [["Prepared", "prepared"], ["Actived", "active"], ["Finished", "finish"]]

select_boolean: [["True", 1], ["False", 0]]
select_one: [["Select", 0]]
select_all_questions: "All questions"
stick_type_list: [['All reports', 0],['by leader', 1], ['by user', 2], ['All stickies', 3]]
stick_type:
  stick_by_leader: 1
  stick_by_user: 2
  all_sticky_report: 3
  all_report: 0

state:
  prepared: "prepared"
  actived: "actived"
  finished: "finished"

payslip:
  accessable: ["B120011"]
users:
  gender: ["Male", "Female"]
  marital_status: ["Single", "Married"]
  contract_types: ["Probationary", "Apprenticeship", "6 months - 1 year", "3 years", "Indefinite term"]
  ranking: ["A", "B", "C", "D", "E"]
evaluation:
  eval: "Evaluation"
  long_sort: "Long And Short Term Goal"