role_category_list: ["Backoffice", "Development"]
role_category:
  backoffice: "Backoffice"
  development: "Development"

role_list: ["HR", "Manager", "Leader", "Member"]
role:
  hr: "HR"
  manager: "Manager"
  leader: "Leader"
  member: "Member"

positions: [["Chief", "chief"], ["Manager", "manager"], ["Submanager", "submanager"], ["Leader", "leader"], ["Subleader", "subleader"], ["Member", "member"]]

master_datas: ["groups", "report_categories"]

project:
  states: [["Prepared", "prepared"], ["Actived", "active"], ["Finished", "finish"]]

select_boolean: [["True", 1], ["False", 0]]
