role_category_list: ["Backoffice", "Development"]
role_category:
  backoffice: "Backoffice"
  development: "Development"

role_list: ["HR", "Manager", "Leader", "Member"]
role:
  hr: "HR"
  manager: "Manager"
  leader: "Leader"
  member: "Member"

positions: [["Chief", "chief"], ["Manager", "manager"], ["Submanager", "submanager"], ["Leader", "leader"], ["Subleader", "subleader"], ["Member", "member"]]

master_datas: ["groups", "report_categories"]

project:
  states: [["Prepared", "prepared"], ["Actived", "active"], ["Finished", "finish"]]

select_boolean: [["True", 1], ["False", 0]]

stick_type_list: [['Stickied by leader', 1], ['Stickied by user', 2], ['Stickied reports', 3]]
stick_type:
  stick_by_leader: 1
  stick_by_user: 2
  all_sticky_report: 3

state:
  prepared: "prepared"
  actived: "actived"
  finished: "finished"

payslip:
  accessable: ["B120011"]
